# Project: Histogram
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = Histogram_private.res
OBJ      = Histogram/Histogram.o $(RES)
LINKOBJ  = Histogram/Histogram.o $(RES)
LIBS     = -L"E:/PortableApps/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib" -L"E:/PortableApps/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/PortableApps/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"E:/PortableApps/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/PortableApps/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/PortableApps/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"E:/PortableApps/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/PortableApps/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/PortableApps/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Histogram.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Histogram/Histogram.o: Histogram/Histogram.cpp
	$(CC) -c Histogram/Histogram.cpp -o Histogram/Histogram.o $(CFLAGS)

Histogram_private.res: Histogram_private.rc 
	$(WINDRES) -i Histogram_private.rc --input-format=rc -o Histogram_private.res -O coff 

